CREATE TABLE DMU."ProtocolCrossoverOption" (
  "Protocol_Crossover_Option_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Crossover_Option_Name" varchar2(255) NOT NULL,

   CONSTRAINT PK_PROTOCOL_CROSSOVER_OPTION_ID PRIMARY KEY ("Protocol_Crossover_Option_Id")
);

ALTER TABLE "ProtocolMapping" ADD "Protocol_Crossover_Option_Id" number;