CREATE TABLE "ProtocolCategoryStatus" (
  "Protocol_Category_Status_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Category_Status_Name" varchar2(4000),
  "Is_Active" char(1),
  "Create_Date" timestamp,
  
  CONSTRAINT PK_PROFILE_CATEGORY_STATUS_ID PRIMARY KEY("Protocol_Category_Status_Id")
);

CREATE TABLE "THORDataCategory" (
  "THOR_Data_Category_Id" varchar2(100),
  "Category_Name" varchar2(4000),
  "Is_Multi_Form" char(1),
  "Sort_Order" int,
  "Is_Active" char(1),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
  CONSTRAINT PK_THOR_DATA_CATEGORY_ID PRIMARY KEY("THOR_Data_Category_Id")
);

CREATE TABLE "Profile" (
  "Profile_Id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Profile_Name" varchar2(4000),
  "Profile_Version" number,
  "Profile_Id_Source" number,
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
  CONSTRAINT PK_PROFILE_ID PRIMARY KEY("Profile_Id")
);

CREATE TABLE "ProtocolDataSystem" (
  "Protocol_Data_System_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Data_System_Name" varchar2(4000),
  "Sort_Order" int,
  "Is_Active" Char(1),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
  CONSTRAINT PK_PROTOCOL_DATA_SYSTEM_ID PRIMARY KEY("Protocol_Data_System_Id")
);


CREATE TABLE "ProtocolMappingStatus" (
  "Protocol_Mapping_Status_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Status_Name" varchar2(4000),
  "Is_Active" char(1),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
  CONSTRAINT PK_PROTOCOL_MAPPING_STATUS_ID PRIMARY KEY("Protocol_Mapping_Status_Id")
);

CREATE TABLE "ProtocolMapping" (
  "Protocol_Mapping_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Profile_Id" number,
  "THOR_Study_Id" number,
  "Mapping_Version" number,
  "Source_Protocol_Mapping_Id" number,
  "Is_Published" char(1),
  "Protocol_Mapping_Status_Id" number,
  "Billing_Code" varchar2(4000),
  "Title" varchar2(4000),
  "Sponsor" varchar2(4000),
  "Protocol_Data_System_Id" number,
  "Date_Format" varchar2(4000),
  "Data_File_Folder" varchar2(4000),
  "Create_Date" timestamp,
  
  CONSTRAINT PK_PROTOCOL_MAPPING_PROTOCOL_MAPPING_ID PRIMARY KEY("Protocol_Mapping_Id")
);


CREATE TABLE "ProtocolDataCategory" (
  "Protocol_Category_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "THOR_Data_Category_Id" varchar2(100),
  "Protocol_Category_Status_Id" number,
  "Create_Date" timestamp,
  "Updated_Date" timestamp,

  CONSTRAINT PK_PROTOCOL_DATA_CATEGORY_ID_PROTOCOL_CATEGORY_ID PRIMARY KEY("Protocol_Category_Id")
);

CREATE TABLE "Profile_DataCategory" (
  "Profile_Data_Cateogy_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Profile_Id" number,
  "THOR_Data_Category_Id" varchar2(100),
  "Create_Date" timestamp,
  
   CONSTRAINT PK_PROFILE_DATA_CATEGORY_PROFILE_DATA_CATEGORY_ID PRIMARY KEY("Profile_Data_Cateogy_Id")
);

CREATE TABLE "THORFieldType" (
  "THOR_Field_Type_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Field_Type_Name" varchar2(4000),
  "Is_Active" char(1),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
  CONSTRAINT PK_THOR_FIELD_TYPE_THOR_FIELD_TYPE_ID PRIMARY KEY("THOR_Field_Type_Id")
);

CREATE TABLE "THORDictionary" (
  "THOR_Dictionary_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Dictionary_Name" varchar2(4000),
  "Dictionary_Option" varchar2(4000),
  "Dictonary_Value" varchar2(4000),
  "Sort_Order" int,
  "Is_Active" char(1),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
  CONSTRAINT PK_THOR_DICTIONARY_THOR_DICTIONARY_ID PRIMARY KEY("THOR_Dictionary_Id")
);

CREATE TABLE "THORField" (
  "THOR_Field_Id" varchar2(100),
  "THOR_Data_Category_Id" varchar2(100),
  "Field_Name" varchar2(4000),
  "Field_Label" varchar2(4000),
  "THOR_Field_Type" int,
  "Is_Derivable" char(1),
  "THOR_Dictionary_Id" int,
  "Is_Multi_Form" char(1),
  "Sort_Order" int,
  "Is_Active" char(1),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
  CONSTRAINT PK_THOR_FIELD_THOR_FIELD_ID PRIMARY KEY("THOR_Field_Id")
);

CREATE TABLE "Profile_Field" (
  "Profile_Field_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Profile_Id" number,
  "THOR_Field_Id" varchar2(100),
  "Create_Date" timestamp,

 CONSTRAINT PK_PROFILE_FIELD_PROFILE_FIELD_ID PRIMARY KEY("Profile_Field_Id")
);

CREATE TABLE "ProtocolEDCForm" (
  "Protocol_EDC_Form_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "EDC_Form_Identifier" varchar2(4000),
  "EDC_Form_Name" varchar2(4000),
  "Create_Date" timestamp,
  "Update_Date" timestamp,

 CONSTRAINT PK_PROTOCOL_EDC_FORM_PROTOCOL_EDC_FORM_ID PRIMARY KEY("Protocol_EDC_Form_Id")
);

CREATE TABLE "ProtocolEDCField" (
  "Protocol_EDC_Field_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_EDC_Form_Id" number,
  "EDC_Field_Identifier" varchar2(4000),
  "EDC_Field_Name" varchar2(4000),
  "EDC_Dictionary_Name" varchar2(4000),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
 CONSTRAINT PK_PROTOCOL_EDC_FIELD_PROTOCOL_EDC_FIELD_ID PRIMARY KEY("Protocol_EDC_Field_Id")
);

CREATE TABLE "ProtocolFieldMapping" (
  "Protocol_Field_Mapping_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "THOR_Field_Id" varchar2(100),
  "Protocol_EDC_Field_Id" number,
  "Create_Date" timestamp,
  "Update_Date" timestamp,

 CONSTRAINT PK_PROTOCOL_FIELD_MAPPING_PROTOCOL_FIELD_MAPPING_ID PRIMARY KEY("Protocol_Field_Mapping_Id")
);

CREATE TABLE "ProtocolEDCDictionary" (
  "Protocol_EDC_Dictionary_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "EDC_Item_Id" varchar2(4000),
  "EDC_Item_Name" varchar2(4000),
  "EDC_Dictionary_Name" varchar2(4000),
  "Create_Date" timestamp,
  "Updated_Date" timestamp,

CONSTRAINT PK_PROTOCOL_EDC_DICTIONARY_PROTOCOL_EDC_DICTIONARY_ID PRIMARY KEY("Protocol_EDC_Dictionary_Id")
);

CREATE TABLE "ProtocolDictionaryMapping" (
  "Protocol_Dictionary_Mapping_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Field_Mapping_Id" number,
  "Protocol_EDC_Dictionary_Id" number,
  "THOR_Dictionary_Id" number,
  "Create_Date" timestamp,

 CONSTRAINT PK_PROTOCOL_DICTIONARY_MAPPING_PROTOCOL_DICTIONARY_MAPPING_ID PRIMARY KEY("Protocol_Dictionary_Mapping_Id")
);

CREATE TABLE "ProtocolFormMapping" (
  "Protocol_Form_Mapping_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_EDC_Form_Id" number,
  "Is_Primary_Form" char(1),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
 CONSTRAINT PK_PROTOCOL_FORM_MAPPING_PROTOCOL_FORM_MAPPING_ID PRIMARY KEY("Protocol_Form_Mapping_Id")
);

CREATE TABLE "ProtocolField" (
  "Protocol_Field_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "THOR_Field_Id" varchar2(100),
  "Format" varchar2(4000),
  "Is_Enabled" char(1),
  "Is_Required" char(1),
  "Can_Be_Dictionary" char(1),
  "Is_Multi_Form" char(1),
  "Create_Date" timestamp,
  "Updated_Date" timestamp,

 CONSTRAINT PK_PROTOCOL_FIELD_PROTOCOL_FIELD_ID PRIMARY KEY("Protocol_Field_Id")
);

CREATE TABLE "ProtocolDisease" (
  "Protocol_Disease_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "Disease_Name" varchar2(4000),
  "Meddra_Code" varchar2(4000),
  "Create_Date" timestamp,
  "Update_Date" timestamp,

 CONSTRAINT PK_PROTOCOL_DISEASE_PROTOCOL_DISEASE_ID PRIMARY KEY("Protocol_Disease_Id")
);

CREATE TABLE "ProtocolSubGroup" (
  "Protocol_Sub_Group_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "Sub_Group_Code" varchar2(4000),
  "Description" varchar2(4000),
  "Create_Date" timestamp,
  "Update_Date" timestamp,

 CONSTRAINT PK_PROTOCOL_SUB_GROUP_PROTOCOL_SUB_GROUP_ID PRIMARY KEY("Protocol_Sub_Group_Id")
);

CREATE TABLE "ProtocolAgent" (
  "Protocol_Agent_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "Nsc_Number" varchar2(4000),
  "Agent_Name" varchar2(4000),
  "Create_Date" timestamp,
  "Update_Date" timestamp,

 CONSTRAINT PK_AGENT_PROTOCOL_AGENT_ID PRIMARY KEY("Protocol_Agent_Id")
);

CREATE TABLE "ProtocolTac" (
  "Protocol_Tac_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "Tac_Code" varchar2(4000),
  "Tac_Description" varchar2(4000),
  "Create_Date" timestamp,
  "Update_Date" timestamp,

 CONSTRAINT PK_PROTOCOL_TAC_PROTOCOL_TAC_ID PRIMARY KEY("Protocol_Tac_Id")
);

CREATE TABLE "ProtocolPhase" (
  "Protocol_Phase_Id" number GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "Protocol_Mapping_Id" number,
  "Sort_Order" int,
  "Is_Randomized" char(1),
  "Create_Date" timestamp,
  "Update_Date" timestamp,
  
   CONSTRAINT PK_PROTOCOL_PHASE_PROTOCOL_PHASE_ID PRIMARY KEY("Protocol_Phase_Id")
);


  ALTER TABLE "ProtocolMapping" ADD (
  CONSTRAINT "FK_PROTOCOLMAPPING_PROFILE_PROFILE_ID"
    FOREIGN KEY ("Profile_Id")
      REFERENCES "Profile"("Profile_Id"),
  
  CONSTRAINT "FK_PROTOCOLMAPPING_PROTOCOL_DATA_SYSTEM_ID"
    FOREIGN KEY ("Protocol_Data_System_Id")
    REFERENCES "ProtocolDataSystem"("Protocol_Data_System_Id"),

  CONSTRAINT "FK_PROTOCOLMAPPING_SOURCE_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Source_Protocol_Mapping_Id")
    REFERENCES "ProtocolMapping"("Protocol_Mapping_Id"),

  CONSTRAINT "FK_PROTOCOLMAPPING_PROTOCOL_MAPPING_STATUS_ID"
    FOREIGN KEY ("Protocol_Mapping_Status_Id")
    REFERENCES "ProtocolMappingStatus"("Protocol_Mapping_Status_Id")
);


  ALTER TABLE "ProtocolDataCategory" ADD (
  CONSTRAINT "FK_PROTOCOLDATACATEGORY_PROTOCOL_CATEGORY_STATUS_ID"
    FOREIGN KEY ("Protocol_Category_Status_Id")
      REFERENCES "ProtocolCategoryStatus"("Protocol_Category_Status_Id"),
      
  CONSTRAINT "FK_PROTOCOLDATACATEGORY_THOR_DATA_CATEGORY_ID"
    FOREIGN KEY ("THOR_Data_Category_Id")
      REFERENCES "THORDataCategory"("THOR_Data_Category_Id"),
      
  CONSTRAINT "FK_PROTOCOLDATACATEGORY_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);


ALTER TABLE "Profile_DataCategory" ADD (
  CONSTRAINT "FK_PROFILEDATACATEGORY_PROFILE_ID"
    FOREIGN KEY ("Profile_Id")
      REFERENCES "Profile"("Profile_Id"),
      
  CONSTRAINT "FK_PROFILEDATACATEGORY_THOR_DATA_CATEGORY_ID"
    FOREIGN KEY ("THOR_Data_Category_Id")
      REFERENCES "THORDataCategory"("THOR_Data_Category_Id")
);

ALTER TABLE "THORField" ADD (
  CONSTRAINT "FK_THORFIELD_THOR_DATA_CATEGORY_ID"
    FOREIGN KEY ("THOR_Data_Category_Id")
      REFERENCES "THORDataCategory"("THOR_Data_Category_Id"),

  CONSTRAINT "FK_THORFIELD_THOR_FIELD_TYPE"
    FOREIGN KEY ("THOR_Field_Type")
      REFERENCES "THORFieldType"("THOR_Field_Type_Id"),

  CONSTRAINT "FK_THORFIELD_THOR_DICTIONARY_ID"
    FOREIGN KEY ("THOR_Dictionary_Id")
      REFERENCES "THORDictionary"("THOR_Dictionary_Id")
);

ALTER TABLE "Profile_Field" ADD (
  CONSTRAINT "FK_PROFILEFIELD_PROFILE_ID"
    FOREIGN KEY ("Profile_Id")
      REFERENCES "Profile"("Profile_Id"),

  CONSTRAINT "FK_PROFILEFIELD_THOR_FIELD_ID"
    FOREIGN KEY ("THOR_Field_Id")
      REFERENCES "THORField"("THOR_Field_Id")
);

ALTER TABLE "ProtocolEDCForm" ADD (
  CONSTRAINT "FK_PROTOCOLEDCFORM_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);

ALTER TABLE "ProtocolEDCField" ADD (
  CONSTRAINT "FK_PROTOCOLEDCFIELD_PROTOCOL_EDC_FORM_ID"
    FOREIGN KEY ("Protocol_EDC_Form_Id")
      REFERENCES "ProtocolEDCForm"("Protocol_EDC_Form_Id")
);

ALTER TABLE "ProtocolFieldMapping" ADD (
  CONSTRAINT "FK_PROTOCOLFIELDMAPPING_PROTOCOL_EDC_FIELD_ID"
    FOREIGN KEY ("Protocol_EDC_Field_Id")
      REFERENCES "ProtocolEDCField"("Protocol_EDC_Field_Id"),

  CONSTRAINT "FK_PROTOCOLFIELDMAPPING_THOR_FIELD_ID"
    FOREIGN KEY ("THOR_Field_Id")
      REFERENCES "THORField"("THOR_Field_Id")
);

ALTER TABLE "ProtocolEDCDictionary" ADD (
  CONSTRAINT "FK_PROTOCOLEDCDICTIONARY_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);

ALTER TABLE "ProtocolDictionaryMapping" ADD (
  CONSTRAINT "FK_PROTOCOLDICTIONARYMAPPING_PROTOCOL_FIELD_MAPPING_ID"
    FOREIGN KEY ("Protocol_Field_Mapping_Id")
      REFERENCES "ProtocolFieldMapping"("Protocol_Field_Mapping_Id"),

  CONSTRAINT "FK_PROTOCOLDICTIONARYMAPPING_PROTOCOL_EDC_DICTIONARY_ID"
    FOREIGN KEY ("Protocol_EDC_Dictionary_Id")
      REFERENCES "ProtocolEDCDictionary"("Protocol_EDC_Dictionary_Id"),

  CONSTRAINT "FK_PROTOCOLDICTIONARYMAPPING_THOR_DICTIONARY_ID"
    FOREIGN KEY ("THOR_Dictionary_Id")
      REFERENCES "THORDictionary"("THOR_Dictionary_Id")
);

ALTER TABLE "ProtocolFormMapping" ADD (
  CONSTRAINT "FK_PROTOCOLFORMMAPPING_PROTOCOL_EDC_FORM_ID"
    FOREIGN KEY ("Protocol_EDC_Form_Id")
      REFERENCES "ProtocolEDCForm"("Protocol_EDC_Form_Id")
);

ALTER TABLE "ProtocolField" ADD (
  CONSTRAINT "FK_PROTOCOLFIELD_THOR_FIELD_ID"
    FOREIGN KEY ("THOR_Field_Id")
      REFERENCES "THORField"("THOR_Field_Id"),

  CONSTRAINT "FK_PROTOCOLFIELD_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);

ALTER TABLE "ProtocolDisease" ADD (
  CONSTRAINT "FK_PROTOCOLDISEASE_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);

ALTER TABLE "ProtocolSubGroup" ADD (
  CONSTRAINT "FK_PROTOCOLSUBGROUP_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);

ALTER TABLE "ProtocolAgent" ADD (
  CONSTRAINT "FK_PROTOCOLAGENT_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);

ALTER TABLE "ProtocolTac" ADD (
  CONSTRAINT "FK_PROTOCOLTAC_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);

ALTER TABLE "ProtocolPhase" ADD (
  CONSTRAINT "FK_PROTOCOLPHASE_PROTOCOL_MAPPING_ID"
    FOREIGN KEY ("Protocol_Mapping_Id")
      REFERENCES "ProtocolMapping"("Protocol_Mapping_Id")
);