name: Check Commit Messages

on:
  pull_request:
    branches:
      - main

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed to get all commits
      - name: Check commit messages
        run: |
          git log --pretty=%s | while read commit; do
            if [[ ! "$commit" =~ ^(feat|fix|docs|style|refactor|test|chore)(\\([a-z]+\\))?:.*$ ]]; then
              echo "Error: Invalid commit message: $commit"
              exit 1
            fi
          done