name: Prowler Security Assessment

on:
  schedule:
    - cron: '0 0 1 * *'  # Run daily at midnight
  workflow_dispatch:      # Allow manual triggers            

jobs:
  prowler-security-assessment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for AWS OIDC authentication
      contents: read    # Required to checkout repository
      security-events: write  # Required for GitHub Security tab

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PROD }}
          aws-region: us-east-1

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Prowler
        run: |
          python -m pip install --upgrade pip
          pip install prowler-cloud

      - name: Run Prowler Assessment
        run: |
          mkdir -p prowler_output
          prowler aws \
            --output-formats html json-ocsf \
            --output-directory prowler_output \
            --region us-east-1 \
            --severity high medium \
            --compliance cis_2.0_aws aws_well_architected_framework_security_pillar_aws \
            --log-level ERROR \
            --no-banner
            --ignore-exit-code-3

      - name: List output directory
        run: ls -la prowler_output/
        if: success() || failure()

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: prowler-report
          path: prowler_output/prowler-*.html
          retention-days: 30
